Worldmap scripting
SuperTux/supertux pull request #1691
Opened 2021-03-07 15:46 UTC by Semphriss

This PR gives access to the `settings` object in worldmaps, thus permitting usage of ambient lighting and music from scripting.

2021-04-19 18:37 UTC, tobbi requested changes

2021-04-19 18:37 UTC, tobbi commented on src/scripting/worldmap.cpp
> +WorldMap::get_tux_x()
const

2021-04-19 18:37 UTC, tobbi commented on src/scripting/worldmap.cpp
> +WorldMap::get_tux_y()
const

2021-04-19 18:37 UTC, tobbi commented on src/scripting/worldmap.hpp
> +  float get_tux_x();
mark const here as well.

2021-04-19 18:37 UTC, tobbi commented on src/worldmap/worldmap.cpp
> +{
const

2021-04-19 18:37 UTC, tobbi commented on src/worldmap/worldmap.hpp
> +  Vector get_tux_pos();
...and const

2021-04-30 19:50 UTC, tobbi approved these changes

2021-04-30 19:51 UTC, tobbi commented
Please rebase.

2021-05-17 20:35 UTC, Semphriss commented
Superseded by #1692, which got properly rebased

2021-05-17 20:35 UTC, closed without merging