List contrib levels by offical, community and user
SuperTux/supertux pull request #1790
Opened 2021-07-13 07:51 UTC by mrkubax10

This pull request adds feature from #720 and #1344

2021-11-14 10:29 UTC, tobbi commented
Can you please rebase this? I think it's worth considering this.

2021-11-28 17:56 UTC, Semphriss requested changes

2021-11-28 17:56 UTC, Semphriss commented on src/supertux/menu/sorted_contrib_menu.hpp
> +  SortedContribMenu(std::vector<std::unique_ptr<World>>& worlds, std::string contrib_type, std::string title, std::string empty_message);
`const std::string&`

2021-11-28 17:56 UTC, Semphriss commented on src/supertux/menu/sorted_contrib_menu.cpp
> +      }
There's a lot of similarities in both parts of the `if`; isn't it possible to move some of it outside?

Possibly use the `?` operator if there isn't too many differences.

2021-11-28 18:48 UTC, Semphriss requested changes

2021-11-28 18:48 UTC, Semphriss commented on src/supertux/menu/sorted_contrib_menu.cpp
> +      add_entry(world_id++, title_stream.str()).set_help(desc.str());
These all seem to be strings - what are the string streams for?

2021-11-29 06:50 UTC, Semphriss approved these changes

2021-11-29 06:53 UTC, Semphriss commented
Extra idea if it sounds interesting: Given the category dedicated to the user's personal creations and the addition of the add-on creator in merged #1890, do you think it'd be feasible to populate the former with instances of the latter? E. g., fill the user contribs with the add-ons that the user packaged themselves.

2021-11-30 07:35 UTC, mrkubax10 commented
Originally I wanted to show user made levelsets in user category so I think it wouldn't work.

2021-12-12 18:32 UTC, tobbi commented
Please rebase this so we can merge it!

2021-12-28 17:29 UTC, merged