Improved management of mobile controls + made them available on all platforms
SuperTux/supertux pull request #2030
Opened 2021-12-27 09:25 UTC by Semphriss

2021-12-27 20:38 UTC, tobbi requested changes

2021-12-27 20:38 UTC, tobbi commented on CMakeLists.txt
> +  option(HIDE_NONMOBILE_OPTIONS "Hide options that are impractical on mobile decives (e. g. chainging screen resolution)" ON)
Typo: changing

2021-12-27 20:38 UTC, tobbi commented on CMakeLists.txt
> +  option(HIDE_NONMOBILE_OPTIONS "Hide options that are impractical on mobile decives (e. g. chainging screen resolution)" OFF)
as above: typo.

2021-12-27 21:49 UTC, Narre commented on CMakeLists.txt
> +  option(HIDE_NONMOBILE_OPTIONS "Hide options that are impractical on mobile decives (e. g. chainging screen resolution)" ON)
I also see "decives". Same below.

2021-12-29 11:09 UTC, tobbi approved these changes
Looking good from what I can see.

2022-01-11 15:23 UTC, merged