Detect touchscreen when enabling mobile controller
SuperTux/supertux pull request #2098
Opened 2022-01-15 12:49 UTC by mrkubax10

Fixes issue when mobile controller is enabled by default on devices without touchscreen

2022-01-15 17:18 UTC, Semphriss reviewed
CMakeLists.txt defiles a `SHOW_MOBILE_CONTROLS` (or similar) which I somehow forgot to use here.

2022-01-30 21:58 UTC, Semphriss commented
On second though (or rather, 10th though after those two weeks), I believe it might indeed be wiser to consider if SDL detects any touch device rather than using a macro.

2022-01-30 22:03 UTC, mrkubax10 commented
I will do that then

2022-02-18 02:11 UTC, Semphriss requested changes

2022-02-18 02:11 UTC, Semphriss commented on CMakeLists.txt
> +if (UBUNTU_TOUCH)
`UBUNTU_TOUCH OR ANDROID` here would be preferable

2022-02-18 16:40 UTC, Semphriss approved these changes

2022-02-22 11:10 UTC, merged