Complete overhaul of all forest tilesets + extras
SuperTux/supertux pull request #2136
Opened 2022-02-04 12:01 UTC by Rusty-Box

This PR provides heavy changes to all level assets used for **Rooted Forest**, as well as re-introduce the old ghost forest theme as the new **Corrupted Forest**.

---

**Those changes include the following:**
- Revamped forest tileset
- Revamped underground forest tileset
- New corrupted forest tileset
- New corrupted underground forest tileset
- New Ghost Tree roots tileset
- Updated trees for both normal and corrupted forest
- Updated background assets for both normal and corrupted forest
- Updated spikevine graphics
- Autotiling for all major forest tilesets
- New goal houses for both normal and corrupted forest
- Remove all the unneeded/outdated graphics

---

_Note: Theses changes will break some of the background assets in all levels using the older tilesets! Those will require manual updating!_

2022-02-04 16:23 UTC, Rusty-Box commented
> were roots.png added back?

If you don't consider the commit "Re-add underground root tiles" a lie, then yes :D

2022-03-02 15:26 UTC, Rusty-Box commented
A first "patch" for the ever expanding tileset changes is up now!

---

**This patch inlcudes the following:**

- Updated snow surface tileset
- Improved ice cave tileset
- Theme specific block overlays
- Updated castle tilesets
- New Ruins tileset
- Wall torch variant for torch object
- Floor tile for goal post
- Normal and corrupted flowers for the forest theme
- New sign to indicate the requirement of bombs
- Removal of more old/unneeded graphics

2022-03-19 19:05 UTC, Semphriss commented
From #2175 : Reminder to do secret goal posts :stuck_out_tongue:

2022-09-20 02:56 UTC, jonfx1007 requested changes
After playing around with the tileset update patch for a good while, I have a number of suggestions to increase retrocompatibility by trying to preserve old tile structures as much as possible. You can see the changes to tile IDs line-by-line in the tiles.strf file. Sorry if it gets a bit annoying; I didn't see a good way to do multi-line suggestions in Github. 
Obviously it isn't possible to preserve all old tiles; for example, the forest trees can't be salvaged. But I tried to avoid breaking tiles where possible.
The autotiles.satc file will still need to be updated; I'm willing to help with that if/when changes to tile IDs are accepted.

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +      2647 2648 2649 2665
```suggestion
      2655 2647 2656 2648

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  2650 2651 2652 2666
```suggestion
	  2659 2651 2660 2652

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  2653 2654 2655 2663
```suggestion
	  2662 2664 2661 2663

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  2656 2657 2658 2664
```suggestion
	  2658 2667 2657 2666

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  2659 2660 0    0
```suggestion
	  2649 2650 0    0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  2661 2662 0    0
```suggestion
	  2653 2654 0    0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  0    2667 0    0
```suggestion
	  0    2665 0    0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1746 1747 1748 0
```suggestion
	  1760 1761 1749 0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1749 1750 1751 0
```suggestion
	  1754 1756 1757 0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1218 1219 0    0
```suggestion
	  1218 1219 2586    0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  0    1213 1214 0
```suggestion
	  2583 1213 1214 0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +      4339 4340 2005 2006
```suggestion
      4339 4340 1353 1354
      
```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  4337 4338 2007 2008
```suggestion
	  2009 2014 4356 2008

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  2009 2010 2011 2012
```suggestion
	  4337 4334 4348 4344

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	   473  474  475 2013
```suggestion
	   473 1821  474 2013

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	   476  0   4356 4353
```suggestion
	  2012  0   2007 4353

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	   477  478 4357 4354
```suggestion
	  4338 4333 4357 4354

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  4333 4334 4341 4342
```suggestion
	  2005 2010 4341 4342

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  4348 0    4347 4346
```suggestion
	  2011 0    2006 4346

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  4343 101  4344 4355
```suggestion
	   475 1351  476 4355

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1352 2014 1353 1351
```suggestion
	   477 1352  478  101

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1354 1821 4351 4352
```suggestion
	  4347 4343 4351 4352

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1310 1311 0    0
```suggestion
	  1310 1312 0    0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  2946 1312 4434 0
```suggestion
	  2946 1311 4434 0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1754 1755 2091 2093
```suggestion
	  1748 1755 2091 2093

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  3888 3889 1756 1758
```suggestion
	  3888 3889 1750 1758

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  3890 3891 1757 1759
```suggestion
	  3890 3891 1751 1759

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  3892 3893 1760 1761
```suggestion
	  3892 3893 1746 1747

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1779 1780 1781 1783
```suggestion
	  1779 1780 1781 1802

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1784 1785 1786 1798
```suggestion
	  1784 1787 1795 1798

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1789 1790 1792 1793
```suggestion
	  1801 1790 1792 1783

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1801 1782 1799 1800
```suggestion
	  1775 1782 1799 1800

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1802 1795 1805 1804
```suggestion
	  1774 1797 1805 1804

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1774 1776 1796 1797
```suggestion
	  1793 1776 1803 1808

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1775 0    0    0
```suggestion
	  1789 0    0    0

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1777 1778 1803 1808
```suggestion
	  1791 1785 1796 1786

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1764 1765 3908 3909
```suggestion
	  3269 3270 3908 3909

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1766 1767 1787 1791
```suggestion
	  3259 3260 1778 1777

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1768 1769 3903 3904
```suggestion
	  3271 3272 3903 3904

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1770 1771 3910 3911
```suggestion
	  1772 1773 3910 3911

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1772 1773 2214 2215
```suggestion
	  2212 2213 2214 2215

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  3269 3270 2218 2219
```suggestion
	  1764 1765 2218 2219

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  3259 3260 2220 2221
```suggestion
	  1766 1767 2220 2221

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  3271 3272 2222 2223
```suggestion
	  1768 1769 2222 2223

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  2212 2213 2224 2225
```suggestion
	  1770 1771 2224 2225

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  295  296  297  298
```suggestion
	  297  295  298  296

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1478 1477 2261 2262
```suggestion
	  2263 2264 2261 2262

```

2022-09-20 02:56 UTC, jonfx1007 commented on data/images/tiles.strf
> +	  1503 1510 2263 2264
```suggestion
	  1503 1510 1477 1478

```

2022-10-06 07:15 UTC, merged