Add Conveyor Belt object
SuperTux/supertux pull request #2290
Opened 2022-08-26 20:19 UTC by Raoul1808

This PR adds conveyor belts, a new object that shifts entities in a certain direction at a certain rate.

They have variable length and speed and can shift entities left or right. The conveyor can also be controlled through a script to start or stop the conveyor, change its speed or direction.

Some things may need more polish, like for example extending the texture/animation so it can be seamless over longer belts.

Any feedback is welcome, especially on the code. I'm very new to adding new objects into the game.

2022-09-10 07:20 UTC, mrkubax10 commented
Could you fix compilation issues?

2022-09-10 08:32 UTC, Raoul1808 commented
I just changed the way the conveyor belt shift objects, but there's still the issue of some enemies turning around at the end of the conveyor belt (it only affects enemies that stay on their platform), I don't really know how to tackle this

2022-10-07 03:43 UTC, weluvgoatz requested changes
This is pretty well done and they are very fun to play with.  Conveyor belts could work good in World 4.  However I do have some requests:

1) The graphics are unfitting.  You can honestly get away with the current tiled approach and don't need a seamless texture but the graphic itself should fit better with our current graphic style.  Maybe get a graphic designer on this.
2) When you extend a conveyor belt in the editor, you cannot grab on to the extended part with the tooltip, only the original 1x1 tile part.  I think fixing this has something to do with after_editor_set() (which is or is similar to a function).
3) You already know this, but the stay-on-platform enemies linger weirdly on the platforms.  Maybe there should be an override in which they can be ejected from conveyor belts?

Overall good job!

2022-11-19 10:29 UTC, mrkubax10 requested changes
I just noticed that files `src/object/conveyor_belt.hpp`, `src/object/conveyor_belt.cpp`, `src/scripting/conveyor_belt.hpp` and `src/scripting/conveyor_belt.cpp` have wrong indentation (4 spaces instead of 2)

2023-06-04 19:59 UTC, mrkubax10 approved these changes

2023-06-04 20:17 UTC, Vankata453 requested changes

2023-06-04 20:17 UTC, Vankata453 commented on src/object/conveyor_belt.cpp
> +  m_direction(Direction::LEFT),
Direction member variables are mostly named `m_dir` in the code, so this one could be renamed to `m_dir` as well. Do this only if you wish to.

2023-06-04 20:17 UTC, Vankata453 commented on src/object/conveyor_belt.cpp
> +    m_sprite->set_action((m_direction == Direction::LEFT ? "left" : "right"));
`set_action(m_direction)`, also to be changed for other such calls in the file.

2023-06-04 20:17 UTC, Vankata453 commented on src/object/conveyor_belt.hpp
> +#include "supertux/moving_object.hpp"
Move these two includes to the top, separated by an empty line from the current ones, as they are base classes for `ConveyorBelt`.

2023-06-04 20:17 UTC, Vankata453 commented on src/object/conveyor_belt.hpp
> +
Two redundant empty lines, remove if you wish to.

2023-06-04 20:17 UTC, Vankata453 commented on src/scripting/conveyor_belt.hpp
The scripting file is missing documentation as a whole, see other scripting files for reference.

2023-06-04 20:17 UTC, Vankata453 commented on src/supertux/game_object_factory.cpp
>    add_factory<CloudParticleSystem>("particles-clouds");
Swap these two lines to achieve alphabetical sorting.

2023-06-20 17:14 UTC, Vankata453 approved these changes

2023-06-30 17:26 UTC, weluvgoatz approved these changes

2023-06-30 18:19 UTC, merged