Pause target timer via scripting
SuperTux/supertux pull request #2513
Opened 2023-07-06 01:32 UTC by tobbi

Closes #2504

2023-07-06 08:54 UTC, mrkubax10 approved these changes

2023-07-06 08:58 UTC, Vankata453 commented on src/scripting/functions.hpp
> + * Pauses the target timer
Add a full stop.

2023-07-06 08:58 UTC, Vankata453 commented on src/scripting/functions.hpp
> + * Resumes the target timer
Also add a full stop.

2023-07-06 09:00 UTC, Vankata453 commented
Also believe that these functions would be better suited for the Level class in scripting.

2023-07-21 19:58 UTC, Vankata453 requested changes
The new functions for the `Level` scripting class have to be added into the `Level` Squirrel class definition in `data/scripts/default.nut`, so they are accessible via `Level.{function}`.

2023-07-31 10:03 UTC, Vankata453 commented on src/supertux/game_session.cpp
> +  for (const auto& obj : m_currentsector->get_objects())
`m_currentsector->get_objects_by_type<LevelTime>()`

2023-07-31 10:03 UTC, Vankata453 commented on src/supertux/game_session.cpp
> +      }
Could be done with no curly brackets.

2023-07-31 17:45 UTC, Vankata453 approved these changes

2023-08-01 08:09 UTC, mrkubax10 approved these changes

2023-08-01 16:29 UTC, merged