Ability to set bonus block coin sprite for coin, coin rain and coin explosion
SuperTux/supertux pull request #2546
Opened 2023-07-18 09:06 UTC by MatusGuy

This should close #2487

2023-07-18 18:19 UTC, Rusty-Box approved these changes

2023-07-18 18:25 UTC, Vankata453 approved these changes

2023-07-18 18:25 UTC, Vankata453 commented on src/object/coin_explode.cpp
> +#include "sprite/sprite_manager.hpp"
Unused include.

2023-07-19 09:43 UTC, Vankata453 requested changes

2023-07-19 09:43 UTC, Vankata453 commented on src/object/bonus_block.cpp
> +  m_coin_sprite = "images/objects/coin/coin.sprite";
The variable should rather be initialized in the member initialization list.

2023-07-19 18:16 UTC, mrkubax10 approved these changes

2023-07-20 09:05 UTC, Vankata453 approved these changes

2023-07-20 09:21 UTC, merged