Corrupted Granito
SuperTux/supertux pull request #2663
Opened 2023-10-19 12:10 UTC by Rusty-Box

Corrupted Granit will be a hostile version of the friendly Granito NPC (#2635)
They have different forms with different behaviors.

- Small, replacing Skullyhop as the default variant of the "hopping" enemy type
- Big, a stationary enemy, exploding and bursting into spiky roots if Tux remains too close for too long
- Hive, a variant of the Dispenser object used to dispense Small Corrupted Granito and visually fit in with the enviornment
- DartTrap, a new default variant of the DartTrap enemy

**Note: The original versions of certain enemy types, i.e. Skullyhops + DartTrap will remain in the game and re-added as object types!**

TODO

[ ] - Corrupted Small Granito sprites

Mock-up video:

https://github.com/SuperTux/supertux/assets/20615048/19f3443f-b028-46a1-93c7-aa396b6bccb1

https://github.com/SuperTux/supertux/assets/20615048/45ffe640-b603-4bc6-af81-c1c4d5d618e0

2023-10-19 12:56 UTC, FILIPOKonGithup commented
R.I.P poor Granito that got corrupted and exploded. he will be missed :(

2023-10-19 12:59 UTC, Rusty-Box commented
> R.I.P poor Granito that got corrupted and then gets exploded. he will be missed :(

You can still rescue the survivors :)

2023-10-19 17:23 UTC, FILIPOKonGithup commented
also the ghost tree need to be renamed to corrupted tree because the ghost forest in supertux is now renamed to the corrupted forest

2023-10-19 17:25 UTC, tylerandari13 commented
> also the ghost tree need to be renamed to the corrupted tree because the ghost forest in supertux is now renamed to the corrupted forest

I believe they were keeping the name "Ghost Tree" because it had a better ring to it.

2023-10-19 18:13 UTC, Rusty-Box commented
> also the ghost tree need to be renamed to the corrupted tree because the ghost forest in supertux is now renamed to the corrupted forest

Technically speaking, yes you're right, however as mentioned by the comment above "Ghost Tree" just sounds better overall. If we are to change the name (which is not unlikely) it would need to be something else but "Corrupted Tree", especially since it is rather too close to "Corrupted Mr. Tree".

In my opinion, right now, "Ghost Tree" works fine still in a more metaphorical term. A tree with no "soul" a "hollow tree" (actually not a bad name, ngl.) devoid of thought and personality turning its "subjects" into the same lifeless husks.

2023-10-29 17:40 UTC, MatusGuy commented
huh???? I thought this was only reskining!! Another thing I gotta do...

2023-10-29 18:51 UTC, Rusty-Box commented
> huh???? I thought this was only reskining!! Another thing I gotta do...

It is for te most part. The only big coding task is implementing Corrupted Big Granito. The rest is just minor things like object types and immunities

2023-11-15 19:31 UTC, FILIPOKonGithup commented
![image](https://github.com/SuperTux/supertux/assets/119059427/5ab1d447-fd3f-425d-9fa2-e69b46b98d6a)

2023-11-15 19:39 UTC, Rusty-Box commented
@FILIPOKonGithup Does not relate. Does not help. So I advise you to stop that.

2023-11-16 18:25 UTC, FILIPOKonGithup commented
> @FILIPOKonGithup Does not relate. Does not help. So I advise you to stop that.

ik i just wanted to make a fanart of this scrapped zeekling type

2023-11-16 18:26 UTC, Rusty-Box commented
But this is not the place to share it!

2023-11-16 19:25 UTC, FILIPOKonGithup commented
> But this is not the place to share it!

but theres only Code, Issues, Pull request, Discussions, Actions, Projects, Wiki, Security and Insights, and also i am banned from the supertux server

2023-11-16 19:29 UTC, Rusty-Box commented
You also have the forums. But either way, do not post random things in Pull Requests nor Issues. Epsecially if they have nothing to do with the topic at hand.

2023-11-16 19:37 UTC, NickerAban commented
how?? :''/

2023-11-18 20:01 UTC, Rusty-Box commented
We can probably increase the trigger radius by quite a bit. I'd say 5 or 6 tiles.

2023-11-20 23:11 UTC, Rusty-Box commented
- [ ] Fix timer pause for Corrupted Big Granito

2023-11-25 18:49 UTC, mrkubax10 commented on src/badguy/corrupted_granito.cpp
>  //  Copyright (C) 2006 Christoph Sommer <christoph.sommer@2006.expires.deltadevelopment.de>
Since you changed name of this file and made changes you should add yourself to the license header (same for the hpp file).

2023-11-25 18:49 UTC, mrkubax10 commented on src/badguy/corrupted_granito_big.cpp
> +const float SHAKE_TIME = 0.1f; // seconds
These constants can be marked as `static`.

2023-11-25 18:49 UTC, mrkubax10 commented on src/badguy/corrupted_granito_big.cpp
> +  bool crack = try_cracking();
`const bool`.

2023-11-25 18:49 UTC, mrkubax10 commented on src/badguy/corrupted_granito_big.cpp
> +  Vector plrmid = plr->get_bbox().get_middle();
These variables can be marked as `const`.

2023-11-25 18:49 UTC, mrkubax10 commented on src/badguy/corrupted_granito_big.cpp
> +                                                                   get_collision_object());
You can use variables defined above instead of getting them again.

2023-11-25 18:49 UTC, mrkubax10 commented on src/badguy/corrupted_granito_big.cpp
> +  for (std::string action : pieces)
This can be replaced with `const std::vector` and normal for: `for (size_t i = 0; i<particles; i++)`.

2023-11-25 18:49 UTC, mrkubax10 commented on src/supertux/timer.cpp
> +void Timer::unpause()
`resume` would be a better name.

2023-11-25 19:25 UTC, Vankata453 approved these changes

2023-11-25 20:20 UTC, mrkubax10 approved these changes

2023-11-25 20:30 UTC, tobbi commented on src/badguy/corrupted_granito.cpp
> +  if ((state == STANDING) && (recover_timer.check()))
Remove superfluous parentheses.

2023-11-25 20:30 UTC, tobbi commented on src/badguy/corrupted_granito.cpp
> +  if ((state == CHARGING) && (m_sprite->animation_done()))
same here

2023-11-25 20:34 UTC, tobbi requested changes
May he please fix the thi

2023-11-28 17:10 UTC, merged

2023-11-28 17:39 UTC, MatusGuy commented
Lets go