Save VSync setting
SuperTux/supertux pull request #2781
Opened 2024-02-13 20:07 UTC by tobbi

Fixes #2780

I'm not sure if this is the right approach, as we seem to be checking for the best possible vsync value earlier and picking one.

What's saved is: boolean yes / no: Check for vsync and not the exact vsync value.

2024-02-13 20:13 UTC, MatusGuy commented
Thanks tobbi

2024-02-18 11:13 UTC, MatusGuy requested changes

2024-02-18 11:13 UTC, MatusGuy commented on src/supertux/gameconfig.cpp
> +  vsync(),
Initialize this to something like 1

2024-02-18 17:24 UTC, mrkubax10 approved these changes

2024-02-19 20:17 UTC, MatusGuy requested changes
Something is horribly wrong about this. The program crashes upon close with this call stack:
```
Error: signal 11:
supertux2(_ZN12ErrorHandler17print_stack_traceEv+0x2f)[0x562d557935df]
supertux2(_ZN12ErrorHandler12handle_errorEi+0x3b)[0x562d5579366b]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f5bbee42520]
supertux2(_ZN6Config4saveEv+0x1109)[0x562d557ae319]
supertux2(_ZN15ConfigSubsystemD1Ev+0x16)[0x562d555a3c76]
supertux2(_ZN4MainD1Ev+0x524)[0x562d555076a4]
supertux2(+0x254919)[0x562d55505919]
supertux2(main+0x6d)[0x562d554d17bd]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f5bbee29d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f5bbee29e40]
supertux2(_start+0x2e)[0x562d5550584e]
```

Could this be because you changed a boolean to an integer? If that's the case then we could make a new setting and deprecate the old one.

This pr also started doing weird things like saving to `~/.supertux2/config`, but I'm going to ignore that because i think that wasan issue on my end.

Take a closer look.

2024-02-19 20:20 UTC, Vankata453 commented
At a first glance, I'd assume the issue is that `VideoSystem` has already been destroyed by the time the config is destroyed.

2024-02-20 23:33 UTC, tobbi commented
Okay, please try again.

2024-02-21 18:58 UTC, MatusGuy requested changes
It looks like it doesn't crash on exit anymore. But it still doesn't save. It does look like it saves to the config file, but doesn't choose the correct option in the settings menu and instead always chooses on.

2024-04-30 09:28 UTC, mrkubax10 approved these changes

2024-05-01 11:34 UTC, MatusGuy approved these changes

2024-05-01 11:55 UTC, merged