Allow for control of Tux's fancy idle animations via scripting
SuperTux/supertux pull request #3112
Opened 2024-11-25 20:34 UTC by bruhmoent

Closes #3053

Fancy idle animations being wiggling, scratching, etc.

2024-12-01 05:50 UTC, swagtoy commented
Would you mind if I cherrypicked this in #3116 and we closed this? Up to you...

2024-12-11 15:50 UTC, bruhmoent commented
> Would you mind if I cherrypicked this in #3116 and we closed this? Up to you...

Sure

2024-12-11 16:51 UTC, swagtoy commented
Okay :) I'll do it soon, and I will credit this PR for any readers

2025-06-10 08:59 UTC, Frostwithasideofsalt requested changes
-bug with tux's idle freezing when fancy idle is turned off

2025-06-14 10:04 UTC, Frostwithasideofsalt approved these changes
fully works

2025-06-14 12:02 UTC, Hypernoot commented
There is just one issue: If I call `disable_fancy_idling` while Tux is wiggling, he won't stop doing that and eventually gets stuck in a single frame of his animation.

2025-07-07 17:24 UTC, Hypernoot approved these changes
workz nouw

2025-07-08 16:41 UTC, merged